import {EVENTS,eventById,validMatch,standings,entryCount} from './ranking.mjs';
const KEY='jbs-beginner-v1';
const eventIds=EVENTS.filter(e=>e.id!=='overall').map(e=>e.id);
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const initial=()=>({schema:1,activeEditionId:'classic-2026',editions:[{id:'classic-2026',name:'BACKGAMMON CLASSIC 2026',players:[],matches:[],dates:Object.fromEntries(EVENTS.map(e=>[e.id,e.date]))}]});
let data;try{data=JSON.parse(localStorage.getItem(KEY)||'null')}catch{data=null}
if(!data || data.schema!==1 || !Array.isArray(data.editions))data=initial();
let tab='players',entryEvent='day1',rankEvent='day1',outEvent='day1',historySearch='',playerSearch='',rosterSearch='',editingMatch=null,editingPlayer=null,editingEntries=null;
const ed=()=>data.editions.find(e=>e.id===data.activeEditionId)||data.editions[0];
const evLabel=(id)=>eventById(id)?.label||id;
const summaryId=(id)=>`${id}`;
const player=(id)=>ed().players.find(x=>x.id===id);
const playerLabel=id=>{const p=player(id);return p?`#${p.id} ${p.name}`:`#${id}（未登録）`};
const formatRate=n=>`${(n*100).toFixed(1)}%`;
const dayName=id=>({'day1':'Day1','day2':'Day2','day3':'Day3'}[id]||id);
function save(){try{localStorage.setItem(KEY,JSON.stringify(data))}catch(e){alert('ブラウザに保存できません。JSONバックアップを出力してください。')}renderEditionPicker();}
function notice(msg){const n=$('notice');n.textContent=msg;n.classList.add('show');setTimeout(()=>n.classList.remove('show'),4000)}
function eventSelect(selected,overall=false,id='event-picker'){return `<select id="${id}">${EVENTS.filter(e=>overall||e.id!=='overall').map(e=>`<option value="${e.id}" ${e.id===selected?'selected':''}>${esc(e.label)}</option>`).join('')}</select>`}
function playerOptions(selected=null){return `<option value="">選手を選択</option>`+[...ed().players].sort((a,b)=>(a.kana||a.name).localeCompare(b.kana||b.name,'ja')).map(p=>`<option value="${p.id}" ${p.id===selected?'selected':''}>${esc(`#${p.id} ${p.name}`)}</option>`).join('')}
function renderEditionPicker(){const box=$('edition-picker');box.innerHTML=data.editions.map(e=>`<option value="${esc(e.id)}" ${e.id===ed()?.id?'selected':''}>${esc(e.name)}</option>`).join('')}
function render(){document.querySelectorAll('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));$('app').innerHTML=({entry:renderEntry,manage:renderManage,players:renderPlayers,rank:renderRank,export:renderExport})[tab]();}
function dateFor(eventId){return ed().dates?.[eventId]||(ed().id==='classic-2026'?eventById(eventId)?.date:'')||''}
function resultsFor(event){return ed().matches.filter(x=>x.event===event)}
function side(m){return m.sa===m.sb?'引き分け':(m.sa>m.sb ? playerLabel(m.a):playerLabel(m.b))}
function renderEntry(){const e=eventById(entryEvent),matches=resultsFor(entryEvent);const current=editingMatch?ed().matches.find(x=>x.id===editingMatch):null;
 const first=current?.a||null,second=current?.b||null;
 const sel=e.kind==='two' ? (current?`${current.sa}-${current.sb}`:'2-0') : (current?`${Math.max(current.sa,current.sb)}`:'1');
 const winSecond=current&&current.sb>current.sa;
 const pts=(e.kind==='cube'?[1,2,3,4,6,8,12]:[1,2,3]);
 const formResult=e.kind==='two'?`<label class="field"><span>試合結果（左選手 - 右選手）</span><select name="result">${['2-0','2-1','1-1','1-2','0-2'].map(x=>`<option ${sel===x?'selected':''}>${x}</option>`).join('')}</select></label>`:`<div class="field"><span>勝者</span><label class="checkline"><input type="checkbox" name="secondWinner" ${winSecond?'checked':''}> 右側の選手を勝者にする</label></div><label class="field"><span>勝者得点</span><select name="points">${pts.map(x=>`<option value="${x}" ${sel==x?'selected':''}>${x}点</option>`).join('')}</select></label>`;
 const shown=matches.filter(m=>!historySearch||`${playerLabel(m.a)} ${playerLabel(m.b)}`.toLocaleLowerCase().includes(historySearch.toLocaleLowerCase())).slice().reverse().slice(0,80);
 return `<div class="grid2"><div class="box"><label class="field"><span>大会を選択</span>${eventSelect(entryEvent,false,'entry-event')}</label><div class="overview"><div class="metric"><strong>${matches.length}</strong><span>登録済み試合</span></div><div class="metric"><strong>${standings(ed(),entryEvent).length}</strong><span>対戦済み選手</span></div></div><h3>${current?'試合結果の修正':'試合結果を登録'}</h3><form id="match-form"><div class="scoreline"><label class="field"><span>${e.kind==='two'?'左選手':'選手①'}</span><select name="a" required>${playerOptions(first)}</select></label><span class="vs">VS</span><label class="field"><span>${e.kind==='two'?'右選手':'選手②'}</span><select name="b" required>${playerOptions(second)}</select></label></div>${formResult}<div class="btnset"><button type="submit" class="btn primary">${current?'結果を更新':'結果を登録'}</button>${current?'<button type="button" class="btn" data-action="cancel-match">編集を取り消す</button>':''}</div></form></div><div class="box"><div class="section-head"><h3>登録履歴</h3><span class="muted">直近80件（全 ${matches.length}件）</span></div><input id="history-filter" placeholder="選手名・番号で検索" value="${esc(historySearch)}" class="select-wide" aria-label="登録履歴検索"><div class="table-scroll spaced">${shown.length?`<table class="data-table"><thead><tr><th>No.</th><th>対戦選手</th><th>結果</th><th>操作</th></tr></thead><tbody>${shown.map(m=>`<tr><td>#${esc(m.id)}</td><td>${esc(playerLabel(m.a))}<div class="muted">vs ${esc(playerLabel(m.b))}</div></td><td>${m.sa} - ${m.sb}</td><td class="row-actions"><button class="btn small" data-action="edit-match" data-id="${esc(m.id)}">修正</button> <button class="btn small danger" data-action="delete-match" data-id="${esc(m.id)}">削除</button></td></tr>`).join('')}</tbody></table>`:'<div class="empty">該当する試合がありません</div>'}</div></div></div>`
}
function statsTable(eventId,preview=false){const rows=standings(ed(),eventId),isTwo=eventId==='two',overall=eventId==='overall';
 if(!rows.length)return '<div class="empty">表示できる成績がありません</div>';
 return `<div class="table-scroll"><table class="data-table"><thead><tr><th>順位</th><th>氏名</th><th>選手No.</th><th>試合</th><th>勝</th><th>負</th>${isTwo?'<th>引分</th>':''}<th>勝越</th><th>勝率</th>${!isTwo?'<th>得点</th><th>失点</th><th>得失点</th>':''}${overall?'<th>採用Day</th>':''}</tr></thead><tbody>${rows.map(r=>`<tr class="${r.rank<=3?'podium':''}"><td><strong>${r.rank}</strong></td><td class="player-name">${esc(r.name)}</td><td>${r.id}</td><td>${r.matches}</td><td>${r.wins}</td><td>${r.losses}</td>${isTwo?`<td>${r.draws}</td>`:''}<td class="${r.spread>=0?'pos':'neg'}">${r.spread>0?'+':''}${r.spread}</td><td>${formatRate(r.rate)}</td>${!isTwo?`<td>${r.scored}</td><td>${r.conceded}</td><td class="${r.diff>=0?'pos':'neg'}">${r.diff>0?'+':''}${r.diff}</td>`:''}${overall?`<td>${(r.selectedDays||[]).map(dayName).join('＋')}</td>`:''}</tr>`).join('')}</tbody></table></div>`;
}
function renderRank(){const e=eventById(rankEvent),rows=standings(ed(),rankEvent),n=rankEvent==='overall'?null:entryCount(ed(),rankEvent);
 return `<div class="box"><div class="field-inline"><label class="field rank-event"><span>表示するランキング</span>${eventSelect(rankEvent,true,'rank-event')}</label></div><div class="overview"><div class="metric"><strong>${rows.length}</strong><span>${rankEvent==='overall'?'総合順位対象者':'対戦済み選手'}</span></div>${n!==null?`<div class="metric"><strong>${n}</strong><span>試合数</span></div>`:''}${rows.length?`<div class="metric"><strong>${esc(rows[0].name)}</strong><span>暫定1位</span></div>`:''}</div><div class="rule">${e.kind==='two'?'勝越試合数 → 勝率（引き分けを除く勝敗で計算） → 試合数':e.kind==='overall'?'Day3で対戦し、Day3を含む2日以上で試合のある選手が対象。得失点差の上位2大会を合算。順位は 得失点差 → 勝越試合数 → 勝率。':'得失点差 → 勝越試合数 → 勝率'}。同点の場合は同順位です。</div><div class="spaced">${statsTable(rankEvent)}</div></div>`;
}
function renderManage(){const e=ed();
 const selected=editingEntries?e.players.find(p=>p.id===editingEntries):null;
 const filtered=e.players.filter(p=>!playerSearch||`${p.id} ${p.name} ${p.kana||''}`.toLocaleLowerCase().includes(playerSearch.toLocaleLowerCase())).sort((a,b)=>a.id-b.id);
 const counts=eventIds.map(id=>`<div class="metric"><strong>${entryCount(e,id)}</strong><span>${eventById(id).short} 試合</span></div>`).join('');
 return `<div class="overview"><div class="metric"><strong>${e.players.length}</strong><span>登録選手</span></div>${counts}</div><div class="grid2"><div class="box"><h3>出場登録</h3><form id="entries-form"><label class="field"><span>対象選手</span><select id="entries-player" name="player" required><option value="">選手を選択</option>${[...e.players].sort((a,b)=>a.id-b.id).map(p=>`<option value="${p.id}" ${selected?.id===p.id?'selected':''}>${esc(`#${p.id} ${p.name}`)}</option>`).join('')}</select></label><div class="player-grid">${eventIds.map(id=>`<label class="checkline"><input type="checkbox" name="entries" value="${id}" ${selected?.entries?.includes(id)?'checked':''}>${esc(eventById(id).short)}</label>`).join('')}</div><div class="btnset"><button class="btn primary" type="submit" ${selected?'':'disabled'}>出場登録を保存</button></div></form><p class="muted">選手の新規登録や番号・名前・読み方の変更は「選手管理」で行います。</p><hr class="thin"><h3>大会の日付設定</h3><form id="dates-form"><div class="player-grid">${eventIds.map(id=>`<label class="field"><span>${esc(eventById(id).short)}</span><input type="date" name="${id}" value="${esc(e.dates?.[id]||dateFor(id))}"></label>`).join('')}</div><button class="btn" type="submit">日付を保存</button></form><hr class="thin"><h3>バックアップ・大会管理</h3><div class="btnset"><button class="btn" data-action="backup">JSON出力</button><button class="btn" data-action="load">JSON取込</button><button class="btn" data-action="rename-edition">大会名の変更</button><button class="btn danger" data-action="delete-edition">この大会を削除</button></div><p class="muted">別端末とのデータ共有は自動では行われません。JSON出力・取込をご利用ください。</p></div><div class="box"><div class="section-head"><h3>選手別の出場登録（${filtered.length}名）</h3></div><input id="player-filter" placeholder="氏名・ふりがな・選手番号で検索" value="${esc(playerSearch)}" class="select-wide"><div class="table-scroll spaced">${filtered.length?`<table class="data-table"><thead><tr><th>番号</th><th>氏名</th><th>出場大会</th><th>操作</th></tr></thead><tbody>${filtered.map(p=>`<tr><td>${p.id}</td><td>${esc(p.name)}</td><td>${(p.entries||[]).map(x=>esc(eventById(x)?.short||x)).join('、')||'—'}</td><td><button class="btn small" data-action="edit-entries" data-id="${p.id}">変更</button></td></tr>`).join('')}</tbody></table>`:'<div class="empty">該当する選手がいません</div>'}</div></div></div>`;
}
function renderPlayers(){const e=ed(),cur=editingPlayer!==null?player(editingPlayer):null;
 const players=e.players.filter(p=>!rosterSearch||`${p.id} ${p.name} ${p.kana||''}`.toLocaleLowerCase().includes(rosterSearch.toLocaleLowerCase())).sort((a,b)=>a.id-b.id);
 const suggested=Math.max(0,...e.players.map(p=>p.id))+1;
 return `<div class="grid2"><div class="box"><h3>${cur?'選手情報の変更':'選手の追加'}</h3><form id="player-form"><label class="field"><span>番号</span><input name="id" type="number" min="1" max="999999999" step="1" required value="${cur?.id??suggested}"></label><label class="field"><span>名前</span><input name="name" required maxlength="100" placeholder="氏名" value="${esc(cur?.name||'')}"></label><label class="field"><span>読み方</span><input name="kana" maxlength="100" placeholder="ふりがな" value="${esc(cur?.kana||'')}"></label><div class="btnset"><button class="btn primary" type="submit">${cur?'変更を保存':'選手を追加'}</button>${cur?'<button class="btn" type="button" data-action="cancel-player">編集を取り消す</button>':''}</div></form><p class="muted">番号は任意に指定できます。試合記録がある選手の番号を変更した場合も、過去の対戦記録へ自動反映します。</p></div><div class="box"><h3>選手一覧（${players.length}名）</h3><input id="roster-filter" placeholder="番号・名前・読み方で検索" value="${esc(rosterSearch)}" class="select-wide"><div class="table-scroll spaced">${players.length?`<table class="data-table roster-table"><thead><tr><th>番号</th><th>名前</th><th>読み方</th><th>操作</th></tr></thead><tbody>${players.map(p=>`<tr><td>${p.id}</td><td>${esc(p.name)}</td><td>${esc(p.kana||'')}</td><td><button class="btn small" data-action="edit-player" data-id="${p.id}">編集</button> <button class="btn small danger" data-action="delete-player" data-id="${p.id}">削除</button></td></tr>`).join('')}</tbody></table>`:'<div class="empty">該当する選手がいません</div>'}</div></div></div>`;
}
function reportHTML(id){const e=eventById(id);const rows=standings(ed(),id);const date=id==='overall'? dateFor('day3'):dateFor(id);const isTwo=id==='two',overall=id==='overall';
 return `<div class="report"><div class="report-heading"><div class="smallcaps">JAPAN BACKGAMMON SOCIETY</div><h2>${esc(ed().name)}　${esc(e.label)}　成績表</h2><small>${esc(date)}　／　日本バックギャモン協会</small></div><table><thead><tr><th>順位</th><th>氏名</th><th>No.</th><th>試合</th><th>勝</th><th>負</th>${isTwo?'<th>引</th>':''}<th>勝越</th><th>勝率</th>${!isTwo?'<th>得点</th><th>失点</th><th>得失点</th>':''}${overall?'<th>採用Day</th>':''}</tr></thead><tbody>${rows.map(r=>`<tr><td>${r.rank}</td><td>${esc(r.name)}</td><td>${r.id}</td><td>${r.matches}</td><td>${r.wins}</td><td>${r.losses}</td>${isTwo?`<td>${r.draws}</td>`:''}<td>${r.spread>0?'+':''}${r.spread}</td><td>${formatRate(r.rate)}</td>${!isTwo?`<td>${r.scored}</td><td>${r.conceded}</td><td>${r.diff>0?'+':''}${r.diff}</td>`:''}${overall?`<td>${r.selectedDays.map(dayName).join('＋')}</td>`:''}</tr>`).join('')||`<tr><td colspan="12">成績データなし</td></tr>`}</tbody></table><p class="muted" style="margin-top:12px">${rows.length}名　／　${isTwo?'勝越→勝率→試合数':'得失点差→勝越→勝率'}順</p></div>`;
}
function renderExport(){return `<div class="box"><label class="field rank-event"><span>出力する成績表</span>${eventSelect(outEvent,true,'out-event')}</label><div class="btnset"><button class="btn primary" data-action="print">PDF出力・印刷</button><button class="btn" data-action="csv">CSV出力</button></div><p class="muted">PDF出力ボタンからブラウザの印刷画面を開き、「PDFに保存」を選択してください。A4縦で出力します。</p></div>${reportHTML(outEvent)}`}
function matchSave(form){const f=new FormData(form),a=Number(f.get('a')),b=Number(f.get('b'));
 let sa,sb;if(entryEvent==='two'){[sa,sb]=String(f.get('result')).split('-').map(Number)}else{const val=Number(f.get('points'));sa=f.get('secondWinner')?0:val;sb=f.get('secondWinner')?val:0;}
 const m={id:editingMatch||'m'+Date.now()+'-'+Math.random().toString(36).slice(2,8),event:entryEvent,a,b,sa,sb};const err=validMatch(m,new Set(ed().players.map(p=>p.id)));if(err){alert(err);return}
 const repeated=ed().matches.some(x=>x.id!==m.id&&x.event===m.event&&((x.a===a&&x.b===b)||(x.a===b&&x.b===a)));
 if(repeated&&!confirm('この2名は既にこの大会で対戦しています。重複対戦として登録しますか？'))return;
 if(editingMatch){const i=ed().matches.findIndex(x=>x.id===editingMatch);if(i<0)return;ed().matches[i]=m;}else ed().matches.push(m);
 editingMatch=null;save();render();notice('試合結果を保存しました。');
}
function playerSave(form){const f=new FormData(form),rawId=String(f.get('id')||''),name=String(f.get('name')||'').trim(),kana=String(f.get('kana')||'').trim();
 const id=Number(rawId);
 if(!/^\d+$/.test(rawId)||!Number.isSafeInteger(id)||id<1||id>999999999){alert('番号は1以上の整数で入力してください。');return}
 if(!name){alert('名前を入力してください。');return}
 if(ed().players.some(p=>p.id===id&&p.id!==editingPlayer)){alert('この番号はすでに使用されています。');return}
 if(editingPlayer!==null){const p=player(editingPlayer);if(!p)return;
  if(id!==p.id){const used=ed().matches.some(m=>m.a===p.id||m.b===p.id);if(used&&!confirm(`選手番号を #${p.id} から #${id} に変更し、登録済みの試合記録にも反映しますか？`))return;
   for(const m of ed().matches){if(m.a===p.id)m.a=id;if(m.b===p.id)m.b=id}
  }
  if(editingEntries===p.id)editingEntries=id;
  p.id=id;p.name=name;p.kana=kana;
 }else ed().players.push({id,name,kana,entries:[]});
 editingPlayer=null;save();render();notice('選手番号・名前・読み方を保存しました。');
}
function entriesSave(form){const f=new FormData(form),id=Number(f.get('player')),p=player(id);if(!p){alert('対象選手を選択してください。');return}
 p.entries=f.getAll('entries').filter(id=>eventIds.includes(id));editingEntries=p.id;save();render();notice('出場登録を保存しました。');}
function asCSV(id){const isTwo=id==='two',overall=id==='overall';let h=['順位','氏名','選手No.','試合','勝','負'];if(isTwo)h.push('引分');h.push('勝越','勝率');if(!isTwo)h.push('得点','失点','得失点');if(overall)h.push('採用Day');
 const lines=[h,...standings(ed(),id).map(r=>{const a=[r.rank,r.name,r.id,r.matches,r.wins,r.losses];if(isTwo)a.push(r.draws);a.push(r.spread,formatRate(r.rate));if(!isTwo)a.push(r.scored,r.conceded,r.diff);if(overall)a.push(r.selectedDays.map(dayName).join('+'));return a})];
 const safe=s=>{const t=String(s??'');return '"'+(typeof s==='string'&&/^[=+\-@\t\r]/.test(t)?"'":'')+t.replaceAll('"','""')+'"'};return '\ufeff'+lines.map(a=>a.map(safe).join(',')).join('\r\n')}
function download(name,content,type){const blob=new Blob([content],{type}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function timestamp(){const d=new Date(),pad=x=>String(x).padStart(2,'0');return `${d.getFullYear()}${pad(d.getMonth()+1)}${pad(d.getDate())}${pad(d.getHours())}${pad(d.getMinutes())}${pad(d.getSeconds())}`}
function normalizeImport(x){if(!x||x.schema!==1||!Array.isArray(x.editions))throw Error('対応するJSON形式ではありません。');const ids=new Set();for(const e of x.editions){if(typeof e.id!=='string'||typeof e.name!=='string'||ids.has(e.id)||!Array.isArray(e.players)||!Array.isArray(e.matches))throw Error('大会データが不正です。');ids.add(e.id);const pids=new Set();for(const p of e.players){if(!Number.isInteger(p.id)||pids.has(p.id)||!String(p.name||'').trim())throw Error('選手マスタに重複・不正値があります。');pids.add(p.id)}const mids=new Set();for(const m of e.matches){if(typeof m.id!=='string'||mids.has(m.id))throw Error('試合IDの重複があります。');mids.add(m.id);const issue=validMatch(m,pids);if(issue)throw Error(`${e.name}: ${issue}`)}e.dates=e.dates||{};for(const p of e.players){p.entries=Array.isArray(p.entries)?p.entries.filter(v=>eventIds.includes(v)):[]}}return x}
function fileLoad(){const i=document.createElement('input');i.type='file';i.accept='.json,application/json';i.onchange=async()=>{if(!i.files?.length)return;try{const raw=JSON.parse(await i.files[0].text());const imported=normalizeImport(raw);let n=0;for(const e of imported.editions){if(data.editions.some(x=>x.id===e.id)){if(!confirm(`「${e.name}」が存在します。上書きしますか？（操作を取り消せません）`))continue;data.editions=data.editions.filter(x=>x.id!==e.id)}data.editions.push(e);data.activeEditionId=e.id;n++}if(n){save();render();notice(`${n}大会分のデータを取り込みました。`)}else notice('取り込みは行われませんでした。');}catch(e){alert('JSON取込エラー：'+e.message)}};i.click();}
function newEdition(){const name=prompt('新しい大会データの名称','BACKGAMMON CLASSIC 2027');if(!name?.trim())return;const id='edition-'+Date.now();data.editions.push({id,name:name.trim(),players:[],matches:[],dates:{}});data.activeEditionId=id;entryEvent='day1';rankEvent='day1';outEvent='day1';save();render();notice('大会データを作成しました。')}
function onAction(action,id){switch(action){
 case 'edit-match':{const m=ed().matches.find(x=>String(x.id)===String(id));if(!m)return;entryEvent=m.event;editingMatch=m.id;tab='entry';render();window.scrollTo({top:0,behavior:'smooth'});break}
 case 'cancel-match':editingMatch=null;render();break;
 case 'delete-match':if(!confirm('この試合結果を削除しますか？'))return;ed().matches=ed().matches.filter(m=>String(m.id)!==String(id));if(editingMatch===id)editingMatch=null;save();render();notice('試合結果を削除しました。');break;
 case 'edit-player':editingPlayer=Number(id);tab='players';render();window.scrollTo({top:0,behavior:'smooth'});break;
 case 'cancel-player':editingPlayer=null;render();break;
 case 'edit-entries':editingEntries=Number(id);tab='manage';render();window.scrollTo({top:0,behavior:'smooth'});break;
 case 'delete-player':{const n=Number(id);if(ed().matches.some(m=>m.a===n||m.b===n)){alert('この選手には試合記録があります。先に試合結果を削除してください。');return}if(!confirm(`選手 #${n} を削除しますか？`))return;ed().players=ed().players.filter(p=>p.id!==n);if(editingPlayer===n)editingPlayer=null;if(editingEntries===n)editingEntries=null;save();render();notice('選手を削除しました。');break}
 case 'backup':download(`beginner_${timestamp()}.json`,JSON.stringify({schema:1,activeEditionId:data.activeEditionId,editions:data.editions},null,2),'application/json');break;
 case 'load':fileLoad();break;
 case 'rename-edition':{const name=prompt('大会データの名称',ed().name);if(!name?.trim())return;ed().name=name.trim();save();render();break}
 case 'delete-edition':{if(data.editions.length===1){alert('最後の大会は削除できません。');return}if(!confirm(`「${ed().name}」の選手・試合データをすべて削除しますか？`))return;data.editions=data.editions.filter(e=>e.id!==data.activeEditionId);data.activeEditionId=data.editions[0].id;save();render();break}
 case 'print':$('print-area').innerHTML=reportHTML(outEvent);window.print();break;
 case 'csv':download(`beginner_${outEvent}_${timestamp()}.csv`,asCSV(outEvent),'text/csv;charset=utf-8');break;
 }}
document.querySelectorAll('[data-tab]').forEach(b=>b.addEventListener('click',()=>{tab=b.dataset.tab;editingMatch=null;editingPlayer=null;editingEntries=null;render()}));
$('edition-picker').addEventListener('change',e=>{data.activeEditionId=e.target.value;editingMatch=null;editingPlayer=null;editingEntries=null;save();render()});
$('new-edition').addEventListener('click',newEdition);
$('app').addEventListener('submit',e=>{if(e.target.id==='match-form'){e.preventDefault();matchSave(e.target)}else if(e.target.id==='player-form'){e.preventDefault();playerSave(e.target)}else if(e.target.id==='entries-form'){e.preventDefault();entriesSave(e.target)}else if(e.target.id==='dates-form'){e.preventDefault();const f=new FormData(e.target);ed().dates={};for(const id of eventIds)if(f.get(id))ed().dates[id]=String(f.get(id));ed().dates.overall=ed().dates.day3||'';save();render();notice('大会の日付を保存しました。')}});
$('app').addEventListener('change',e=>{if(e.target.id==='entry-event'){entryEvent=e.target.value;editingMatch=null;render()}else if(e.target.id==='rank-event'){rankEvent=e.target.value;render()}else if(e.target.id==='out-event'){outEvent=e.target.value;render()}else if(e.target.id==='entries-player'){editingEntries=e.target.value?Number(e.target.value):null;render()}});
$('app').addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(b)onAction(b.dataset.action,b.dataset.id)});
$('app').addEventListener('input',e=>{if(e.target.id==='history-filter'){historySearch=e.target.value;const sel=e.target.selectionStart;render();$('history-filter')?.focus();$('history-filter')?.setSelectionRange(sel,sel)}else if(e.target.id==='player-filter'){playerSearch=e.target.value;const sel=e.target.selectionStart;render();$('player-filter')?.focus();$('player-filter')?.setSelectionRange(sel,sel)}else if(e.target.id==='roster-filter'){rosterSearch=e.target.value;const sel=e.target.selectionStart;render();$('roster-filter')?.focus();$('roster-filter')?.setSelectionRange(sel,sel)}});
renderEditionPicker();render();
